### ISSUE TITLE
Feature Request: All fields should not change upon changing one field

### ISSUE THREAD

**Issue by VishiNehra** [DonneyF/ubcgrades#2]
Currently, whenever a field (Year/Course department/Course number/ Section) is changed, all the fields to the "right" of that field are changed. However, we don't want this to happen if said configuration exists. 

Example: Changing "2019W CPSC 320 OVERALL" to "2018W CPSC 320 OVERALL" should not make the other fields empty, they should stay as they are, as this section exists. We should display this course's results once the field is changed.

**Comment by DonneyF** [comment]
Hello! Thanks for the suggestion. I'd like to get a bit more information before considering this feature request.

Personally when I want to view yearly changes I use the "Submit by ID" entry point instead of the dropdowns so I can quickly enter the section that I want, although this is not available on mobile. Have you tried using this instead? If you have, do you find using the dropdowns to be easier? If so, why?

**Comment by Goulustis** [comment]
I second this feature (on web). For instance, if I'm looking at: 

2018W, cpsc,, 110, Overall

and I want to change to:
2019W, cpsc,, 110, Overall.

I would be nice if I don't have to re select the [course depertment, course number, section]. Because they are blank after I change 2018W to 2019

**Comment by VishiNehra** [comment]
I prefer the dropdowns because they feel easier somehow, also submit by ID doesn't do OVERALL section for me. In my opinion its just making the users life more difficult by them having to reenter information that shouldn't have disappeared in the first place.
